apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: monitoring
spec:
  project: monitoring
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 1.16.1
    helm:
      releaseName: sealed-secrets
      valueFiles:
      - values-production.yaml  
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubeseal